name: Build & Push Latest image

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  setup-go:
    if: github.event.pull_request.merged == true
    name: setup-go
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Go 1.21.1
        id: go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          go get -v ./...

      - name: Build Go Application
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo apt install build-essential -y
          sudo apt-get clean
          
          # Build etl application          
          GOARCH=amd64 GOOS=linux go build -tags musl -o dataops-takehome
          
          # Build api server
          cd api
          GOARCH=amd64 GOOS=linux go build -tags musl -o dataops-takehome-server

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and Push Docker image
        run: |
          # Build etl application
          docker build -t shiva5128/dataops-takehome-2:latest .
          docker push shiva5128/dataops-takehome-2:latest
          
          # Build api server
          cd api
          docker build -t shiva5128/dataops-takehome-server:latest .
          docker push shiva5128/dataops-takehome-server:latest
          
          # Build api server
          cd ../ui
          docker build -t shiva5128/dataops-takehome-ui:latest .
          docker push shiva5128/dataops-takehome-ui:latest
          
          
          
